# Copyright 2025 Ian Lewis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

plugin:
  - id: "@textlint/textlint-plugin-latex2e"
  - id: "@textlint/textlint-plugin-text"
  - id: "@textlint/textlint-plugin-markdown"
plugins:
  - "latex2e"
filters:
  comments: true
rules:
  spelling:
    language: "en"
    skipPatterns:
      # Company names
      - "/\\bBeProud\\b/g" # Japanese IT company
      - "/\\bCyberAgent\\b/g" # Japanese internet company
      - "/\\bDatatel\\b/g" # Higher education software company
      - "/\\bDeNA\\b/g" # Japanese mobile gaming company
      - "/\\bNavi\\b/g" # EC Navi, Japanese company
      - "/\\bEllucian\\b/g" # Higher education software company
      - "/\\bGijutsu\\b/g" # Gijutsu Hyoronsha, Japanese publisher
      - "/\\bHyoronsha\\b/g" # Gijutsu Hyoronsha, Japanese publisher
      - "/\\bRakuten\\b/g" # Japanese e-commerce company

      # Place names
      - "/\\bFairfax\\b/g" # Fairfax, Virginia
      - "/\\bBridgewater\\b/g" # Bridgewater, Virginia

      # Event names
      - "/\\bKubeCon\\b/g" # Kubernetes conference
      - "/\\bEuroPython\\b/g" # European Python conference
      - "/\\bPyCon\\b/g" # Python conference

      # OSS projects/technologies
      - "/\\bBackbone.js\\b/g" # JavaScript framework
      - "/\\bCoffeeScript\\b/g" # JavaScript dialect
      - "/\\bContainerd\\b/g" # Container runtime
      - "/\\bKnative\\b/g" # Kubernetes-native serverless framework
      - "/\\bKubernetes\\b/g" # Container orchestration platform
      - "/\\bNetlink\\b/g" # Network management for Linux
      - "/\\bRequireJS\\b/g" # JavaScript module loader
      - "/\\bSeccomp\\b/g" # Linux kernel security module
      - "/\\bSigstore\\b/g" # OpenSSF Sigstore project
      - "/\\bgVisor\\b/g" # Google Cloud gVisor project
      - "/\\bminikube\\b/g" # Lightweight Kubernetes cluster
      - "/\\bprocfs\\b/g" # Linux kernel proc filesystem

      # Product names
      - "/\\bBigtable\\b/g" # Google Cloud Bigtable
      - "/\\bConnpass\\b/g" # Event management platform
      - "/\\bSIPSS\\b/g" # Point of Sale Software
      - "/\\bnpm\\b/g" # Node Package Manager

      # Acronyms
      - "/\\bABI\\b/g" # Application Binary Interface
      - "/\\bAPIs?\\b/g" # Application Programming Interface
      - "/\\bBPF\\b/g" # Berkeley Packet Filter
      - "/\\bCFP\\b/g" # Call for Papers
      - "/\\bGDE\\b/g" # Google Developer Expert
      - "/\\bGKE\\b/g" # Google Kubernetes Engine
      - "/\\bNPO\\b/g" # Non-Profit Organization
      - "/\\bOCI\\b/g" # Open Container Initiative
      - "/\\bPOS\\b/g" # Point of Sale
      - "/\\bSLSA\\b/g" # Supply Chain Levels for Software Artifacts
      - "/\\bSSO\\b/g" # Single Sign-On
      - "/\\bXML:FO\\b/g" # XML Formatting Objects

      # Technical terms
      - "/\\bCalVer\\b/g" # Calendar Versioning
      - "/\\bRuntimeClass\\b/g" # Kubernetes RuntimeClass
      - "/\\b[Aa]ddon\\b/g"
      - "/\\b[Bb]ackend\\b/g"
      - "/\\b[Cc]ustomizability\\b/g"
      - "/\\b[Ff]rontend\\b/g"
      - "/\\b[Ss]tylesheet\\b/g"
      - "/\\b[Uu]ntrusted\\b/g"

      - "/\\bAMD64\\b/g"
      - "/\\bARM64\\b/g"
      - "/\\b(CHANGELOG|Changelog)\\b/g"
      - "/\\bCODEOWNER\\b/g"
      - "/\\bCLA\\b/g"
      - "/\\bCLI\\b/g"
      - "/\\bCVSS\\b/g"
      - "/\\bDCO\\b/g"
      - "/\\bPRs?\\b/g"
      - "/\\bUI\\b/g"
      - "/\\bYAML\\b/g"
      - "/\\bCodeQL\\b/g"
      - "/\\bDependabot\\b/g"
      - "/\\bHomebrew\\b/g"
      - "/\\bJavaScript\\b/g"
      - "/\\bMakefile\\b/g"
      - "/\\bNode.js\\b/g"
      - "/\\bOpenSSF\\b/g"
      - "/\\bTODOs?\\b/g"
      - "/\\be2e\\b/g"
      - "/\\bmacOS\\b/g"
      - "/\\bx86-64\\b/g"
      - "/\\b[Ff]ormatters?\\b/g"
      - "/\\b[Ll]inters?\\b/g"
      - "/\\b[Pp]ositivity\\b/g"
      - "/\\b[Pp]re\\b/g"
      - "/\\b[Rr]ebase\\b/g"
      - "/\\b[Rr]eproducibility\\b/g"
      - "/\\b[Rr]ulesets?\\b/g"
      - "/\\b[Rr]untimes?\\b/g"
      - "/\\b[Ss]exualized\\b/g"
      - "/\\b[Ss]ocio-economic\\b/g"
      - "/\\b[Uu]serspace\\b/g"
      - "/\\b[Vv]endored\\b/g"
      - "/\\b[Vv]irtualenv\\b/g"
      - "/\\bv?[0-9]+\\b/g"
      - ":white_check_mark:"
