# Copyright 2025 Ian Lewis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow lets you generate SLSA provenance file for your project.
# The generation satisfies level 3 for the provenance requirements - see https://slsa.dev/spec/v0.1/requirements
# The project is an initiative of the OpenSSF (openssf.org) and is developed at
# https://github.com/slsa-framework/slsa-github-generator.
# The provenance file can be verified using https://github.com/slsa-framework/slsa-verifier.
# For more information about SLSA and how it improves the supply-chain, visit slsa.dev.

name: SLSA generic generator

on:
  workflow_dispatch:
  release:
    types: [created]

permissions: {}

jobs:
  build:
    name: Build artifacts and generate SLSA provenance
    runs-on: ubuntu-latest
    permissions:
      contents: write # To upload to the release.
    outputs:
      digests: ${{ steps.hash.outputs.digests }}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          submodules: true
          persist-credentials: false

      # ========================================================
      #
      # Step 1: Build your artifacts.
      #
      # ========================================================
      - name: Install lualatex
        env:
          TEXLIVE_BASE_VERSION: "2023.20240207-1"
          TEXLIVE_EXTRA_VERSION: "2023.20240207-1"
          TEXLIVE_LANG_VERSION: "2023.20240207-1"
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            --no-install-recommends \
            texlive-latex-base="${TEXLIVE_BASE_VERSION}" \
            texlive-pictures="${TEXLIVE_BASE_VERSION}" \
            texlive-luatex="${TEXLIVE_BASE_VERSION}" \
            texlive-xetex="${TEXLIVE_BASE_VERSION}" \
            texlive-latex-extra="${TEXLIVE_EXTRA_VERSION}" \
            texlive-fonts-extra="${TEXLIVE_EXTRA_VERSION}" \
            texlive-formats-extra="${TEXLIVE_EXTRA_VERSION}" \
            texlive-pstricks="${TEXLIVE_EXTRA_VERSION}" \
            texlive-games="${TEXLIVE_EXTRA_VERSION}" \
            texlive-music="${TEXLIVE_EXTRA_VERSION}" \
            texlive-publishers="${TEXLIVE_EXTRA_VERSION}" \
            texlive-humanities="${TEXLIVE_EXTRA_VERSION}" \
            texlive-science="${TEXLIVE_EXTRA_VERSION}" \
            texlive-lang-all="${TEXLIVE_LANG_VERSION}"

      - name: Build PDF
        run: make Ian_M_Lewis_Resume.pdf Ian_M_Lewis_Resume.ja.pdf

      # ========================================================
      #
      # Step 2: Add a step to generate the provenance subjects
      #         as shown below. Update the sha256 sum arguments
      #         to include all binaries that you generate
      #         provenance for.
      #
      # ========================================================
      - name: Generate subject for provenance
        id: hash
        run: |
          set -euo pipefail

          # Generate the subjects (base64 encoded).
          echo "digests=$(sha256sum Ian_M_Lewis_Resume.pdf Ian_M_Lewis_Resume.ja.pdf | base64 -w0)" >> "${GITHUB_OUTPUT}"

      - name: Upload artifact
        uses: softprops/action-gh-release@6cbd405e2c4e67a21c47fa9e383d020e4e28b836 # v2.3.3
        with:
          files: |
            Ian_M_Lewis_Resume.pdf
            Ian_M_Lewis_Resume.ja.pdf

  provenance:
    needs: [build]
    permissions:
      actions: read # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.1.0
    with:
      base64-subjects: "${{ needs.build.outputs.digests }}"
      upload-assets: true # Optional: Upload to a new release
