# Copyright 2025 Ian Lewis

name: "TODO Issue Reopener"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions: {}

jobs:
  issue-reopener:
    runs-on: ubuntu-latest
    permissions:
      # NOTE: contents: read is necessary for private repositories.
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Issue Reopener
        uses: ianlewis/todo-issue-reopener@d55d48e44cb85664e436abf5bd49addb5b56b8b6 # v1.5.0
