# Copyright 2025 Ian Lewis
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: build

on:
  workflow_call:

permissions: {}

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write # Needed to write a comment to the PR.
    steps:
      - name: Write comment to PR
        if: github.event_name == 'pull_request'
        env:
          PULL_REQUEST_NUM: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment "${PULL_REQUEST_NUM}" -R "${GITHUB_REPOSITORY}" \
            --create-if-none \
            --edit-last \
            --body "### 👷 Build preview processing...

          | Files | Link |
          |-------|------|
          | 🗎 Ian_M_Lewis_Resume.pdf<br>🗎 Ian_M_Lewis_Resume.ja.pdf | Building... | "

      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          submodules: true
          persist-credentials: false

      - uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          python-version-file: ".python-version"

      - name: Install lualatex
        env:
          TEXLIVE_BASE_VERSION: "2023.20240207-1"
          # texlive-latex-extra is required for the titlesec package.
          TEXLIVE_EXTRA_VERSION: "2023.20240207-1"
          TEXLIVE_LANG_VERSION: "2023.20240207-1"
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            --no-install-recommends \
            texlive-latex-base="${TEXLIVE_BASE_VERSION}" \
            texlive-luatex="${TEXLIVE_BASE_VERSION}" \
            texlive-latex-extra="${TEXLIVE_EXTRA_VERSION}" \
            texlive-lang-japanese="${TEXLIVE_LANG_VERSION}"

      - name: Build PDF
        run: make Ian_M_Lewis_Resume.pdf Ian_M_Lewis_Resume.ja.pdf

      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        id: upload
        with:
          name: resume
          retention-days: 14
          if-no-files-found: error
          path: |
            Ian_M_Lewis_Resume.pdf
            Ian_M_Lewis_Resume.ja.pdf

      - name: Write comment to PR
        if: github.event_name == 'pull_request'
        env:
          ARTIFACT_URL: ${{ steps.upload.outputs.artifact-url }}
          PULL_REQUEST_NUM: ${{ github.event.pull_request.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment "${PULL_REQUEST_NUM}" -R "${GITHUB_REPOSITORY}" \
            --create-if-none \
            --edit-last \
            --body "### ✅ Build preview ready

          | Files | Link |
          |-------|------|
          | 🗎 Ian_M_Lewis_Resume.pdf<br>🗎 Ian_M_Lewis_Resume.ja.pdf | ⬇️[Download](${ARTIFACT_URL}) |
          "
